services:
  app:
    image: node:22
    container_name: snake
    volumes:
      - .:/app
    working_dir: /app
    user: "${USER_ID}:${GROUP_ID}"
    tty: true
    ports:
      - "3000:3000"
      - "9229:9229"